menus:
  common:
    navbar:
      market:
        to: market.index

  admin:
    navbar:
      market:
        to: admin.market.section.index
        submenu:
          section:
            to: admin.market.section.index
