menus:
  common:
    navbar:
      market:
        to: market.index

  admin:
    navbar:
      market:
        to: admin.market.sections.index
        submenu:
          sections:
            to: admin.market.sections.index
