router:
  http.get:
    market.index.sell:
      "/market": ~

    market.index.buy:
      "/market/buy": ~

    market.search.sell:
      "/market/search": ~

    market.search.buy:
      "/market/buy/search": ~

    market.new:
      "/market/new(/{draft_id})":
        draft_id: /[0-9a-f]{24}/

    market.section.sell:
      "/market/c{section_hid}":
        section_hid:
          match: /\d+/
          type: integer

    market.section.buy:
      "/market/buy/c{section_hid}":
        section_hid:
          match: /\d+/
          type: integer

    market.item.sell:
      "/market/c{section_hid}/{item_hid}":
        section_hid:
          match: /\d+/
          type: integer
        item_hid:
          match: /\d+/
          type: integer

    market.item.buy:
      "/market/buy/c{section_hid}/{item_hid}":
        section_hid:
          match: /\d+/
          type: integer
        item_hid:
          match: /\d+/
          type: integer

    market.user.sell_active:
      "/member{user_hid}/market":
        user_hid:
          match: /\d+/
          type: 'integer'

    market.user.sell_archived:
      "/member{user_hid}/market/archived":
        user_hid:
          match: /\d+/
          type: 'integer'

    market.user.buy_active:
      "/member{user_hid}/market/buy":
        user_hid:
          match: /\d+/
          type: 'integer'

    market.user.buy_archived:
      "/member{user_hid}/market/buy/archived":
        user_hid:
          match: /\d+/
          type: 'integer'

    admin.market.sections.index:
      "/market/sections": ~

    admin.market.sections.new:
      "/market/sections/new": ~

    admin.market.sections.new_link:
      "/market/sections/new_link": ~

    admin.market.sections.edit:
      "/market/sections/{_id}":
        _id: /[0-9a-f]{24}/
