router:
  http.get:
    market.index.buy:
      "/market": ~

    market.index.wish:
      "/market/wish": ~

    market.all.buy:
      "/market/all": ~

    market.all.wish:
      "/market/wish/all": ~

    market.search.buy:
      "/market/search": ~

    market.search.wish:
      "/market/wish/search": ~

    market.new:
      "/market/new(/{draft_id})":
        draft_id: /[0-9a-f]{24}/

    market.section.buy:
      "/market/cat{section_hid}":
        section_hid:
          match: /\d+/
          type: integer

    market.section.buy.unsubscribe:
      "/market/cat{section_hid}/unsubscribe":
        section_hid:
          match: /\d+/
          type: integer

    market.section.wish:
      "/market/wish/cat{section_hid}":
        section_hid:
          match: /\d+/
          type: integer

    market.section.wish.unsubscribe:
      "/market/wish/cat{section_hid}/unsubscribe":
        section_hid:
          match: /\d+/
          type: integer

    market.item.buy:
      "/market/cat{section_hid}/{item_hid}":
        section_hid:
          match: /\d+/
          type: integer
        item_hid:
          match: /\d+/
          type: integer

    market.item.buy.edit:
      "/market/cat{section_hid}/{item_hid}/edit":
        section_hid:
          match: /\d+/
          type: integer
        item_hid:
          match: /\d+/
          type: integer

    market.item.wish:
      "/market/wish/cat{section_hid}/{item_hid}":
        section_hid:
          match: /\d+/
          type: integer
        item_hid:
          match: /\d+/
          type: integer

    market.item.wish.edit:
      "/market/wish/cat{section_hid}/{item_hid}/edit":
        section_hid:
          match: /\d+/
          type: integer
        item_hid:
          match: /\d+/
          type: integer

    market.user.buy_active:
      "/market/member{user_hid}":
        user_hid:
          match: /\d+/
          type: 'integer'

    market.user.buy_closed:
      "/market/member{user_hid}/closed":
        user_hid:
          match: /\d+/
          type: 'integer'

    market.user.wish_active:
      "/market/member{user_hid}/wish":
        user_hid:
          match: /\d+/
          type: 'integer'

    market.user.wish_closed:
      "/market/member{user_hid}/wish/closed":
        user_hid:
          match: /\d+/
          type: 'integer'

    admin.market.sections.index:
      "/market/sections": ~

    admin.market.sections.new:
      "/market/sections/new": ~

    admin.market.sections.new_link:
      "/market/sections/new_link": ~

    admin.market.sections.edit:
      "/market/sections/{_id}":
        _id: /[0-9a-f]{24}/
