router:
  http.get:
    market.index:
      "/market": ~

    market.section:
      "/market/c{section_hid}":
        section_hid:
          match: /\d+/
          type: integer

    admin.market.sections.index:
      "/market/sections": ~

    admin.market.sections.new:
      "/market/sections/new": ~

    admin.market.sections.new_link:
      "/market/sections/new_link": ~

    admin.market.sections.edit:
      "/market/sections/{_id}":
        _id: /[0-9a-f]{24}/
