market:
  uploads:
    extensions: [ jpg, jpeg, png, gif, svg ]
    jpeg_quality: 75
    gif_animation: true
    max_size: 2000000

    resize:
      orig:
        width: 1280
        skip_size: 300000
        type: jpeg
      sm:
        from: md
        #jpeg_quality: 75
        max_width: 136
        max_height: 120
        type: jpeg

    types:
      png:
        resize:
          orig:
            skip_size: 1000000
            type: png
      gif:
        max_size: 100000
