setting_groups:
  market: ~

  market_editor:
    parent: market

setting_schemas:
  global:
    market_title_min_length:
      type: number
      group_key: market_editor
      category_key: market_item
      default: 10

    market_desc_min_length:
      type: number
      group_key: market_editor
      category_key: market_item
      default: 10

    market_items_min_images:
      type: number
      group_key: market_editor
      category_key: market_item
      default: 0

    market_items_max_images:
      type: number
      group_key: market_editor
      category_key: market_item
      default: 10

    market_items_per_page:
      type: number
      group_key: core_display
      category_key: market
      default: 25
