setting_groups:
  market: ~

  market_general:
    parent: market

  market_editor:
    parent: market

setting_schemas:
  global:
    market_items_expire:
      priority: 10
      group_key: market_general
      category_key: market_common
      type: number
      default: 31 # 1 month

    market_items_reopen_max_age:
      priority: 15
      group_key: market_general
      category_key: market_common
      type: number
      default: 183 # 6 months

    market_drafts_expire:
      priority: 20
      group_key: market_general
      category_key: market_common
      type: number
      default: 7 # 7 days

    market_title_min_length:
      type: number
      group_key: market_editor
      category_key: market_item
      default: 10

    market_desc_min_length:
      type: number
      group_key: market_editor
      category_key: market_item
      default: 10

    market_items_min_images:
      type: number
      group_key: market_editor
      category_key: market_item
      default: 0

    market_items_max_images:
      type: number
      group_key: market_editor
      category_key: market_item
      default: 10

    market_items_per_page:
      type: number
      group_key: core_display
      category_key: market
      default: 25
